NAME = rush-02
SRC = main.c available.c solve.c parsing.c ft_strjoin.c \
	  free_all.c xxxx.c

all: $(NAME)

$(NAME):
	gcc -Wall -Werror -Wextra -o $(NAME) $(SRC)

fclean:
	rm -f $(NAME)

re: fclean all
